### ISSUE TITLE
Any chance of a 2.8 update?

### ISSUE THREAD

**Issue by MarkcusD** [dairin0d/enhanced-3d-cursor#11]

**Comment by dairin0d** [comment]
I won’t be continuing the development of this particular addon. Instead, I'm planning to work on a more broad set of precision modeling utilities (which would likely include some of the Enhanced 3D Cursor features); see [Transform Utils](https://github.com/dairin0d/transform-utils) ([wiki](https://en.blender.org/index.php/Extensions:2.6/Py/Scripts/3D_interaction/BatchTransforms)) for a preview (it's an experimental addon for pre-2.8 Blender).

Unfortunately, I'm going to be very busy at least until May, and even then something like that would take a significant time to develop. So there probably won't be anything to show for quite a while.
