### ISSUE TITLE
re: modal operations

### ISSUE THREAD

**Issue by meta-androcto** [dairin0d/enhanced-3d-cursor#3]
hi, I'm having a think about the modal operations in the script, 
I think what would be good is similar to the screencast keys addon, where you activate the addon, then choose to run the modal operator in the ui, so you can turn on & off the addon when needed from the ui, rather than constant modal running. does that make sense?

**Comment by dairin0d** [comment]
The permanently running modal operator is mostly used to record the cursor location history. I suppose I can add an on/off switch for that.
Or did you mean an on/off switch for the whole addon?

**Comment by meta-androcto** [comment]
Just a switch for the modal would be fine i think, then i'll discuss with senior devs about restoring functionality to the contrib addon, no promises but hopefully it's enough.
Thanks & happy new year to you :)

**Comment by dairin0d** [comment]
Happy new year to you too :-) By the way, what exactly do you mean by "restoring functionality to the contrib addon"? From what I understand, most of the existing addons would have to be significantly rewritten for Blender 2.8 anyway, and until they are, it makes no sense to keep them in contrib.

**Comment by dairin0d** [comment]
One more question: should this option be a global addon preference, a per-file setting, or something else?

**Comment by dairin0d** [comment]
Hm, perhaps a compromise approach would be to make it a global preference which can be temporarily overridden? I.e. the setting will reset to the default state when Blender loads, but after that the user can change it from the UI panel.

**Comment by dairin0d** [comment]
Done!
