### ISSUE TITLE
Shortcut for history undo?

### ISSUE THREAD

**Issue by alanscodelog** [dairin0d/enhanced-3d-cursor#7]
Is there a way to set a shortcut to undo the history or allow snapping to the history trace locations?

**Comment by dairin0d** [comment]
I added operators scene.cursor_3d_history_backward and scene.cursor_3d_history_forward to this repository, so now you will be able to assign shortcuts. Though I'm not sure this is a significant enough feature to update the addon in Blender's addons-contrib repository. I'll probably commit it there when more changes accumulate.
