### ISSUE TITLE
Optional snap unit (snap fraction).

### ISSUE THREAD

**Issue by GitHubington** [dairin0d/enhanced-3d-cursor#9]
As it says in your documentation, if Shift is held, snap to 1/10 of coordinate unit.

Could you add a field? were we can enter optional snap unit (snap fraction), e.g. 100, instead of 10.

**Comment by dairin0d** [comment]
Should it be a user preference, a per-file setting or a per-scene setting?

**Comment by GitHubington** [comment]
It should be a per-file setting, and we should be able to save it in the Startup File.
We should be able to access it in a similar input box next to History Max Size.

**Comment by dairin0d** [comment]
Hmm... Maybe it would be better to use the exiting Blender setting (grid floor subdivisions) for this? It's hard for me to imagine the use-cases when the cursor should snap to a different increment than the objects do.

**Comment by GitHubington** [comment]
The reason why I suggest the optional snap unit/fraction is because, when you zoom all the way down on blender grid, it shows three levels of subdivision; `1`, `1/10 (0.1)`, and `1/100 (0.01)`.

Currently, enhanced 3d cursor cannot snap to the `1/100` subdivision.

An alternative could be to use `Ctrl+Alt+Shift` for the `1/100` subdivision.

**Comment by dairin0d** [comment]
Try the latest commit. I made it so that Ctrl+Shift snaps to 1/10, Ctrl+Alt snaps to 1/100, Ctrl+Shift+Alt snaps to 1/1000 (the actual fraction will depend on grid floor subdivisions). Or should I change it to Ctrl+Shift = 1/10, Ctrl+Alt = 1/10, Ctrl+Shift+Alt = 1/100?

**Comment by GitHubington** [comment]
The latest version is excellent.
Thank you again @dairin0d, for taking the time to look into this.

**Comment by dairin0d** [comment]
:-)
